#!/usr/bin/env bash

host=$1

if [ -z "${host}" ]; then
    echo "Please specify a host"
    exit 1
fi

sudo nixos-generate-config --force --dir ./hosts/${host}
sudo rm  ./hosts/${host}/configuration.nix
