#!/usr/bin/env bash

configurations=($(ls ./.config))

deploy() {
    cp -r "./.config/$1" "${HOME}/.config/$1"
    echo "${HOME}/.config/$1 deployed"
}

./uninstall

for configuration in ${configurations[*]}; do
    deploy $configuration
done

# sudo cp -r ./services/greetd /etc/
# sudo chown -R greeter:greeter /etc/greetd
# echo "greetd deployed"

sudo nixos-rebuild switch --flake .#nixos-z690
