#!/usr/bin/env bash

host=$1

if [ -n "$(ls -A ./hosts/${HOSTNAME})" ]; then
    host=${HOSTNAME}
fi

if [ -z "${host}" ]; then
    echo "Please specify a host"
    exit 1
fi

sudo nixos-rebuild switch --flake .#"${host}" --show-trace
