#!/usr/bin/env bash

configurations=($(ls ./.config))

purge() {
    if [ -d "${HOME}/.config/$1" ]; then
        rm -rf "${HOME}/.config/$1"
    fi

    echo "${HOME}/.config/$1 removed"
}

for configuration in ${configurations[*]}; do
    purge $configuration
done
